# Data prepare

In [72]:
import pandas as pd

In [73]:
csv_file = r'F:\Research\place_connectivity\PCI_2019.csv'

csv_file = r'/media/huan/HD8T/Research/place_conn/county_county_aug2020.tsv'


In [77]:
df = pd.read_csv(csv_file, sep='\t')
df['o_fips'] = df['user_loc']
df['d_fips'] = df['fr_loc']
df['ri'] = df['scaled_sci']
df

user_loc  fr_loc  scaled_sci  o_fips  d_fips        ri
0             1001    1001    13971142    1001    1001  13971142
1             1001    1003      145133    1001    1003    145133
2             1001    1005      200193    1001    1005    200193
3             1001    1007      371688    1001    1007    371688
4             1001    1009       95859    1001    1009     95859
...            ...     ...         ...     ...     ...       ...
10426436     78030   72151       13881   78030   72151     13881
10426437     78030   72153        8328   78030   72153      8328
10426438     78030   78010    11155562   78030   78010  11155562
10426439     78030   78020    14004203   78030   78020  14004203
10426440     78030   78030    37515311   78030   78030  37515311

[10426441 rows x 6 columns]

In [78]:
df_sorted = df[df['o_fips'] != df['d_fips']]

In [79]:
df_sorted['o_d'] = df_sorted.apply(lambda row: str(min(row['o_fips'], row['d_fips'])) + str(max(row['o_fips'], row['d_fips'])), axis=1)

<ipython-input-79-e6e81eb20818>:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [80]:
df_sorted['o_d'] 

1             10011003
2             10011005
3             10011007
4             10011009
5             10011011
               ...    
10426435    7214978030
10426436    7215178030
10426437    7215378030
10426438    7801078030
10426439    7802078030
Name: o_d, Length: 10423212, dtype: object

In [81]:
df_sorted = df_sorted.reset_index()

In [82]:
df_sorted

index  user_loc  fr_loc  scaled_sci  o_fips  d_fips        ri  \
0                1      1001    1003      145133    1001    1003    145133   
1                2      1001    1005      200193    1001    1005    200193   
2                3      1001    1007      371688    1001    1007    371688   
3                4      1001    1009       95859    1001    1009     95859   
4                5      1001    1011      570502    1001    1011    570502   
...            ...       ...     ...         ...     ...     ...       ...   
10423207  10426435     78030   72149       12859   78030   72149     12859   
10423208  10426436     78030   72151       13881   78030   72151     13881   
10423209  10426437     78030   72153        8328   78030   72153      8328   
10423210  10426438     78030   78010    11155562   78030   78010  11155562   
10423211  10426439     78030   78020    14004203   78030   78020  14004203   

                 o_d  
0           10011003  
1           10011005  
2           10011007  
3           10011009  
4           10011011  
...              ...  
10423207  7214978030  
10423208  7215178030  
10423209  7215378030  
10423210  7801078030  
10423211  7802078030  

[10423212 rows x 8 columns]

In [83]:
gby = df_sorted.groupby('o_d')['o_d'].count().to_frame()

In [84]:
gby['o_d'].min()

2

In [85]:
gby['o_d'].max()

2

In [86]:
s = df_sorted.sort_values('o_d')

In [89]:
s[200000:200100]

index  user_loc  fr_loc  scaled_sci  o_fips  d_fips     ri  \
91893      91922      1057   29057        1866    1057   29057   1866   
4874308  4875818     29057    1057        1866   29057    1057   1866   
4877536  4879047     29059    1057        4055   29059    1057   4055   
91894      91923      1057   29059        4055    1057   29059   4055   
91895      91924      1057   29061        2094    1057   29061   2094   
...          ...       ...     ...         ...     ...     ...    ...   
5026024  5027581     29151    1057        1906   29151    1057   1906   
5029252  5030810     29153    1057        1969   29153    1057   1969   
91941      91970      1057   29153        1969    1057   29153   1969   
5032480  5034039     29155    1057       27602   29155    1057  27602   
91942      91971      1057   29155       27602    1057   29155  27602   

               o_d  
91893    105729057  
4874308  105729057  
4877536  105729059  
91894    105729059  
91895    105729061  
...            ...  
5026024  105729151  
5029252  105729153  
91941    105729153  
5032480  105729155  
91942    105729155  

[100 rows x 8 columns]

In [90]:
odd = s[1::2]

In [91]:
gby = odd.groupby('o_d')['o_d'].count().to_frame()

In [92]:
gby['o_d'].max()

1

In [93]:
gby['o_d'].min()

1

In [94]:
odd

index  user_loc  fr_loc  scaled_sci  o_fips  d_fips       ri  \
1020364    1020681     10001   10003      627402   10001   10003   627402   
1020365    1020682     10001   10005     1214534   10001   10005  1214534   
1020366    1020683     10001   11001       15280   10001   11001    15280   
1020367    1020684     10001   12001        4452   10001   12001     4452   
1020368    1020685     10001   12003        2698   10001   12003     2698   
...            ...       ...     ...         ...     ...     ...      ...   
10407387  10410611     72151    9015       14288   72151    9015    14288   
10410615  10413840     72153    9015       14041   72153    9015    14041   
10413843  10417069     78010    9015        3322   78010    9015     3322   
10417071  10420298     78020    9015       10770   78020    9015    10770   
10420299  10423527     78030    9015        3525   78030    9015     3525   

                 o_d  
1020364   1000110003  
1020365   1000110005  
1020366   1000111001  
1020367   1000112001  
1020368   1000112003  
...              ...  
10407387   901572151  
10410615   901572153  
10413843   901578010  
10417071   901578020  
10420299   901578030  

[5211606 rows x 8 columns]

In [95]:
odd.to_csv(r'/media/huan/HD8T/Research/place_conn/SCI_2019_single.csv', index=False)

# AgglomerativeClustering

In [3]:
import pandas as pd
import sklearn
from sklearn.cluster import AgglomerativeClustering
import numpy as np
from natsort import natsorted

import plotly.express as px
import json
from urllib.request import urlopen

with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)
    
def drawmap(df_re):
    fig = px.choropleth_mapbox(df_re, geojson=counties, locations='fips', color='class',
#                                color_discrete_map="Viridis",
#                                color = 'class'
                               range_color=(0, 50),
                               mapbox_style="carto-positron",
                               zoom=3, center = {"lat": 37.0902, "lon": -95.7129},
                               opacity=0.5,
                               labels={'unemp':'unemployment rate'}
                              )
    fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    fig.show()   

In [13]:
csv_file = r'/media/huan/HD8T/Research/place_conn/SCI_2019_single.csv'
csv_file = r'PCI_2019_single.csv'


df = pd.read_csv(csv_file)
df

index  o_fips  d_fips  usercnt  o_fips_usercnt  d_fips_usercnt  \
0           4387   10003   10001     1401           11890            5392   
1           4623   10001   10005     1000            5392            6814   
2          65609   11001   10001      790          147829            5392   
3        1468492   12001   10001       20           13653            5392   
4        3044846   10001   12003        1            5392             415   
...          ...     ...     ...      ...             ...             ...   
1700998  1666614    9015   56023        1            1574             155   
1700999  3059403    9015   56025        1            1574            1480   
1701000  1318874    9015   56037        3            1574             842   
1701001  2861376   56039    9015        2            3761            1574   
1701002   851984    9015   56041        3            1574             372   

              ri             o_d  
0        174.973  10001.010003.0  
1        164.977  10001.010005.0  
2         27.982  10001.011001.0  
3          2.331  10001.012001.0  
4          0.668  10001.012003.0  
...          ...             ...  
1700998    2.025   9015.056023.0  
1700999    0.655   9015.056025.0  
1701000    2.606   9015.056037.0  
1701001    0.822   9015.056039.0  
1701002    3.921   9015.056041.0  

[1701003 rows x 8 columns]

Get fips's index

In [14]:
gby_o = df.groupby('o_fips')['o_fips'].count().index.to_list()
gby_d = df.groupby('d_fips')['d_fips'].count().index.to_list()

In [15]:
gby = gby_o + gby_d

In [16]:
gby_list = gby_o + gby_d
len(gby_list)

6214

In [17]:
gby_set = set(gby_list)
len(gby_set)

3107

In [18]:
gby_list = list(gby_set)
gby_list = natsorted(gby_list)
len(gby_list)

3107

## build distance matrix

In [19]:
dis_mat = np.zeros((len(gby_list[:]), len(gby_list[:])))
print("dis_mat shape:", dis_mat.shape)  

fips_dic = {}                
for i in range(len(gby_list[:])):
#     print(i, gby_list[i])
    fips_dic[gby_list[i]] = i
# print(fips_dic)


dis_mat shape: (3107, 3107)


In [20]:
fips_dic

{1001: 0,
 1003: 1,
 1005: 2,
 1007: 3,
 1009: 4,
 1011: 5,
 1013: 6,
 1015: 7,
 1017: 8,
 1019: 9,
 1021: 10,
 1023: 11,
 1025: 12,
 1027: 13,
 1029: 14,
 1031: 15,
 1033: 16,
 1035: 17,
 1037: 18,
 1039: 19,
 1041: 20,
 1043: 21,
 1045: 22,
 1047: 23,
 1049: 24,
 1051: 25,
 1053: 26,
 1055: 27,
 1057: 28,
 1059: 29,
 1061: 30,
 1063: 31,
 1065: 32,
 1067: 33,
 1069: 34,
 1071: 35,
 1073: 36,
 1075: 37,
 1077: 38,
 1079: 39,
 1081: 40,
 1083: 41,
 1085: 42,
 1087: 43,
 1089: 44,
 1091: 45,
 1093: 46,
 1095: 47,
 1097: 48,
 1099: 49,
 1101: 50,
 1103: 51,
 1105: 52,
 1107: 53,
 1109: 54,
 1111: 55,
 1113: 56,
 1115: 57,
 1117: 58,
 1119: 59,
 1121: 60,
 1123: 61,
 1125: 62,
 1127: 63,
 1129: 64,
 1131: 65,
 1133: 66,
 4001: 67,
 4003: 68,
 4005: 69,
 4007: 70,
 4009: 71,
 4011: 72,
 4012: 73,
 4013: 74,
 4015: 75,
 4017: 76,
 4019: 77,
 4021: 78,
 4023: 79,
 4025: 80,
 4027: 81,
 5001: 82,
 5003: 83,
 5005: 84,
 5007: 85,
 5009: 86,
 5011: 87,
 5013: 88,
 5015: 89,
 5017: 90,
 5019: 91

In [21]:
df

index  o_fips  d_fips  usercnt  o_fips_usercnt  d_fips_usercnt  \
0           4387   10003   10001     1401           11890            5392   
1           4623   10001   10005     1000            5392            6814   
2          65609   11001   10001      790          147829            5392   
3        1468492   12001   10001       20           13653            5392   
4        3044846   10001   12003        1            5392             415   
...          ...     ...     ...      ...             ...             ...   
1700998  1666614    9015   56023        1            1574             155   
1700999  3059403    9015   56025        1            1574            1480   
1701000  1318874    9015   56037        3            1574             842   
1701001  2861376   56039    9015        2            3761            1574   
1701002   851984    9015   56041        3            1574             372   

              ri             o_d  
0        174.973  10001.010003.0  
1        164.977  10001.010005.0  
2         27.982  10001.011001.0  
3          2.331  10001.012001.0  
4          0.668  10001.012003.0  
...          ...             ...  
1700998    2.025   9015.056023.0  
1700999    0.655   9015.056025.0  
1701000    2.606   9015.056037.0  
1701001    0.822   9015.056039.0  
1701002    3.921   9015.056041.0  

[1701003 rows x 8 columns]

In [55]:
for idx, row in df.iterrows():
    interval = 100000
    if idx % interval == 0:
        print(idx)
#     print(row['o_fips'])
    i = fips_dic[row['o_fips']]
    j = fips_dic[row['d_fips']]
    i = int(i)
    j = int(j)
    dis_mat[i, j] = row['ri']
    dis_mat[j, i] = row['ri']
    
print("done")

0
100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
1200000
1300000
1400000
1500000
1600000
1700000
done


In [56]:
import scipy
saved_file = r'/media/huan/HD8T/Research/place_conn/PCI_2019_s_matrix.csv'
s_dis_mat = scipy.sparse.coo_matrix(dis_mat)
scipy.sparse.save_npz(saved_file, s_dis_mat, compressed=True)

In [22]:
dis_mat[0, 1]

0.0

In [23]:
dis_mat.sum()

0.0

In [24]:
df['ri'].sum()

7210579.450000003

In [60]:
df.dtypes

index               int64
o_fips              int64
d_fips              int64
usercnt             int64
o_fips_usercnt      int64
d_fips_usercnt      int64
ri                float64
o_d                object
dtype: object

In [61]:
df_alabama = df[df['o_fips'] < 1200]

In [62]:
df_alabama = df_alabama[df_alabama['d_fips'] < 1200]

In [63]:
df_alabama

index  o_fips  d_fips  usercnt  o_fips_usercnt  d_fips_usercnt  \
5145    40059    1001    1003      167            2200            8386   
5146   101801    1005    1001       18             350            2200   
5147    33181    1007    1001       31             226            2200   
5148    98159    1001    1009       19            2200             371   
5149    92185    1011    1001       10              94            2200   
...       ...     ...     ...      ...             ...             ...   
81111  181948    1129    1125        8              33           10778   
81112  380791    1125    1131        5           10778              40   
81113   71704    1125    1133       43           10778             248   
83373  522757    1129    1127        1              33             867   
83374   11365    1133    1127       40             248             867   

           ri           o_d  
5145   38.880  1001.01003.0  
5146   20.513  1001.01005.0  
5147   43.964  1001.01007.0  
5148   21.031  1001.01009.0  
5149   21.990  1001.01011.0  
...       ...           ...  
81111  13.414  1125.01129.0  
81112   7.615  1125.01131.0  
81113  26.301  1125.01133.0  
83373   5.912  1127.01129.0  
83374  86.263  1127.01133.0  

[1864 rows x 8 columns]

In [64]:
df_alabama.sort_values('ri')

index  o_fips  d_fips  usercnt  o_fips_usercnt  d_fips_usercnt  \
52276  3034571    1087    1095        1            1427            1529   
47078  2357266    1079    1113        1             318            2004   
22352  2247902    1033    1053        1            1246             437   
11234  2229131    1087    1009        1            1427             371   
71227  2183671    1113    1133        1            2004             248   
...        ...     ...     ...      ...             ...             ...   
5168      3908    1051    1001      383            1556            2200   
21256     3611    1045    1031      182             800             726   
27936     3573    1045    1069      331             800            2330   
22362     3162    1033    1077      597            1246            2188   
42359     3146    1073    1117     6126           25410           10478   

            ri           o_d  
52276    0.677  1087.01095.0  
47078    1.253  1079.01113.0  
22352    1.355  1033.01053.0  
11234    1.374  1009.01087.0  
71227    1.418  1113.01133.0  
...        ...           ...  
5168   207.006  1001.01051.0  
21256  238.813  1031.01045.0  
27936  242.440  1045.01069.0  
22362  361.569  1033.01077.0  
42359  375.436  1073.01117.0  

[1864 rows x 8 columns]

## AgglomerativeClustering

In [25]:
dis_mat.max()

0.0

In [66]:
dis_mat.min()

0.0

In [67]:
# dis_mat_inv = 1 / (dis_mat/1000 + 0.0000001)
dis_mat_inv = 1 / (dis_mat + 0.0000001)

dis_mat_inv

array([[1.00000000e+07, 2.57201645e-02, 4.87495732e-02, ...,
        9.04977294e-01, 4.24808818e-01, 4.08830727e-01],
       [2.57201645e-02, 1.00000000e+07, 7.78755543e-02, ...,
        4.41501084e-01, 1.00000000e+07, 1.00000000e+07],
       [4.87495732e-02, 7.78755543e-02, 1.00000000e+07, ...,
        1.00000000e+07, 1.00000000e+07, 1.00000000e+07],
       ...,
       [9.04977294e-01, 4.41501084e-01, 1.00000000e+07, ...,
        1.00000000e+07, 1.74641981e-01, 1.68152007e-01],
       [4.24808818e-01, 1.00000000e+07, 1.00000000e+07, ...,
        1.74641981e-01, 1.00000000e+07, 1.00000000e+07],
       [4.08830727e-01, 1.00000000e+07, 1.00000000e+07, ...,
        1.68152007e-01, 1.00000000e+07, 1.00000000e+07]])

In [68]:
dis_mat_inv_small = dis_mat_inv[:67, :67]
# dis_mat_inv_small = dis_mat_inv[:, :]

dis_mat_inv_small

array([[1.00000000e+07, 2.57201645e-02, 4.87495732e-02, ...,
        1.34716420e-01, 9.88826253e-02, 4.34499238e-02],
       [2.57201645e-02, 1.00000000e+07, 7.78755543e-02, ...,
        7.51540653e-02, 7.23955689e-02, 9.61446006e-02],
       [4.87495732e-02, 7.78755543e-02, 1.00000000e+07, ...,
        1.07469101e-01, 1.00000000e+07, 1.47318796e-01],
       ...,
       [1.34716420e-01, 7.51540653e-02, 1.07469101e-01, ...,
        1.00000000e+07, 1.00000000e+07, 1.00000000e+07],
       [9.88826253e-02, 7.23955689e-02, 1.00000000e+07, ...,
        1.00000000e+07, 1.00000000e+07, 1.00000000e+07],
       [4.34499238e-02, 9.61446006e-02, 1.47318796e-01, ...,
        1.00000000e+07, 1.00000000e+07, 1.00000000e+07]])

In [69]:
dis_mat_inv_small.shape

(67, 67)

In [70]:
conn_mat = np.where(dis_mat_inv_small > 9999.9, 0, 1)
conn_mat

array([[0, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 0, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [71]:
conn_mat.sum()

3728

## with connectivity, linkage = 'average'

In [26]:
import scipy
saved_file = r'/media/huan/HD8T/Research/place_conn/PCI_2019_s_matrix.csv.npz'
s_dis_mat = scipy.sparse.load_npz(saved_file)
# s_dis_mat = scipy.sparse.coo_matrix(dis_mat)
dis_mat = s_dis_mat.todense()
dis_mat

matrix([[ 0.   , 38.88 , 20.513, ...,  1.105,  2.354,  2.446],
        [38.88 ,  0.   , 12.841, ...,  2.265,  0.   ,  0.   ],
        [20.513, 12.841,  0.   , ...,  0.   ,  0.   ,  0.   ],
        ...,
        [ 1.105,  2.265,  0.   , ...,  0.   ,  5.726,  5.947],
        [ 2.354,  0.   ,  0.   , ...,  5.726,  0.   ,  0.   ],
        [ 2.446,  0.   ,  0.   , ...,  5.947,  0.   ,  0.   ]])

In [30]:
dis_mat.sum()

14421158.900000013

In [31]:
df['ri'].sum()

7210579.450000003

In [32]:
dis_mat_inv = 1 / (dis_mat/1000 + 0.0000001)

dis_mat_inv

dis_mat_inv_small = dis_mat_inv[:, :]
conn_mat = np.where(dis_mat_inv_small > 99999.9, 0, 1)
print(conn_mat.shape)
conn_mat

(3107, 3107)


array([[0, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 0, ..., 0, 1, 1],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]])

In [33]:
conn_mat.sum()

3402006

In [46]:

# n_clusters = 48

df_re_list = []

for n_clusters in (20, 48, 50, 75):
    clustering = AgglomerativeClustering(n_clusters=n_clusters,  affinity="precomputed", linkage='single', \

                                       connectivity=conn_mat).fit(dis_mat_inv_small)


    fips_col = []
    for idx, label in enumerate(clustering.labels_):
    #     print(gby_list[idx], label)
        fips_col.append(gby_list[idx])

    df_re = pd.DataFrame(list(zip(fips_col, clustering.labels_)), columns=['fips', 'class'])

    df_re['fips'] = df_re['fips'].astype(str).str.zfill(5)
    df_re['class'] = df_re['class'].astype(str)


    df_re.to_csv(f'/media/huan/HD8T/Research/place_conn/agglomerative_{n_clusters}cluster_single.csv', index=False)
    df_re_list.append((n_clusters, df_re))

    print("finished ", n_clusters)



finished  20
finished  48
finished  50
finished  75


In [ ]:
drawmap(df_re_list[1][1])