# Data prepare

In [3]:
import pandas as pd

In [6]:
csv_file = r'F:\Research\place_connectivity\PCI_2019.csv'

csv_file = r'/media/huan/HD8T/Research/place_conn/county_county_aug2020.tsv'

csv_file = r'K:\OneDrive_USC\OneDrive - University of South Carolina\Research\place_connectivity\world_first_subdivision_pci_2019.csv'

csv_file = r'K:\OneDrive_USC\OneDrive - University of South Carolina\Research\place_connectivity\la_tract_pci_2019.csv'

In [7]:
# df = pd.read_csv(csv_file, sep=',',  names=['o_fips', 'd_fips', 'ri'], header=None)
# df['o_fips'] = df['user_loc']
# df['d_fips'] = df['fr_loc']
# df['ri'] = df['scaled_sci']
df = pd.read_csv(csv_file, sep=',',  names=['o_fips', 'd_fips', "shared_users","fips_1_users","fips_2_users","ri","dir_pci"], header=0)
df

o_fips      d_fips  shared_users  fips_1_users  fips_2_users  \
0        6037214600  6037262802             7           699           359   
1        6037701701  6037228100             1           250            49   
2        6037293202  6037432402             1            71            20   
3        6037621001  6037269601             1           120            76   
4        6037602106  6037601700             1            62            58   
...             ...         ...           ...           ...           ...   
2091867  6071001600  6059088801             2          1026            51   
2091868  6059110111  6037296600             1            41            64   
2091869  6037600100  6037600201             2            18            17   
2091870  6037273600  6037276604            42          3468           422   
2091871  6059110302  6037602900             1            68           125   

              ri  dir_pci  
0         13.974   19.499  
1          9.035   20.408  
2         26.537   50.000  
3         10.471   13.158  
4         16.676   17.241  
...          ...      ...  
2091867    8.743   39.216  
2091868   19.522   15.625  
2091869  114.332  117.647  
2091870   34.718   99.526  
2091871   10.847    8.000  

[2091872 rows x 7 columns]

In [8]:
df_sorted = df[df['o_fips'] != df['d_fips']]

In [9]:
df_sorted['o_d'] = df_sorted.apply(lambda row: str(min(row['o_fips'], row['d_fips'])) + str(max(row['o_fips'], row['d_fips'])), axis=1)

<ipython-input-9-e6e81eb20818>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sorted['o_d'] = df_sorted.apply(lambda row: str(min(row['o_fips'], row['d_fips'])) + str(max(row['o_fips'], row['d_fips'])), axis=1)


In [13]:
df_sorted['o_d'] 

0          6037214600.06037262802.0
1          6037228100.06037701701.0
2          6037293202.06037432402.0
3          6037269601.06037621001.0
4          6037601700.06037602106.0
                     ...           
2089077    6059088801.06071001600.0
2089078    6037296600.06059110111.0
2089079    6037600100.06037600201.0
2089080    6037273600.06037276604.0
2089081    6037602900.06059110302.0
Name: o_d, Length: 2089082, dtype: object

In [14]:
df_sorted = df_sorted.reset_index()

In [15]:
df_sorted

level_0    index      o_fips      d_fips  shared_users  fips_1_users  \
0              0        0  6037214600  6037262802             7           699   
1              1        1  6037701701  6037228100             1           250   
2              2        2  6037293202  6037432402             1            71   
3              3        3  6037621001  6037269601             1           120   
4              4        4  6037602106  6037601700             1            62   
...          ...      ...         ...         ...           ...           ...   
2089077  2089077  2091867  6071001600  6059088801             2          1026   
2089078  2089078  2091868  6059110111  6037296600             1            41   
2089079  2089079  2091869  6037600100  6037600201             2            18   
2089080  2089080  2091870  6037273600  6037276604            42          3468   
2089081  2089081  2091871  6059110302  6037602900             1            68   

         fips_2_users       ri  dir_pci                       o_d  
0                 359   13.974   19.499  6037214600.06037262802.0  
1                  49    9.035   20.408  6037228100.06037701701.0  
2                  20   26.537   50.000  6037293202.06037432402.0  
3                  76   10.471   13.158  6037269601.06037621001.0  
4                  58   16.676   17.241  6037601700.06037602106.0  
...               ...      ...      ...                       ...  
2089077            51    8.743   39.216  6059088801.06071001600.0  
2089078            64   19.522   15.625  6037296600.06059110111.0  
2089079            17  114.332  117.647  6037600100.06037600201.0  
2089080           422   34.718   99.526  6037273600.06037276604.0  
2089081           125   10.847    8.000  6037602900.06059110302.0  

[2089082 rows x 10 columns]

In [16]:
gby = df_sorted.groupby('o_d')['o_d'].count().to_frame()

In [17]:
gby['o_d'].min()

2

In [18]:
gby['o_d'].max()

2

In [19]:
s = df_sorted.sort_values('o_d')

In [20]:
s[200000:200100]

level_0    index      o_fips      d_fips  shared_users  fips_1_users  \
80829      80829    80956  6059075303  6037125310             1           103   
617762    617762   618619  6037125310  6059075303             1           505   
731480    731480   732482  6037125310  6059075401             1           505   
1597036  1597036  1599178  6059075401  6037125310             1            65   
350063    350063   350551  6059075505  6037125310             2           533   
...          ...      ...         ...         ...           ...           ...   
1982543  1982543  1985188  6037125310  6059088601             1           505   
1910820  1910820  1913374  6059088602  6037125310             1           465   
32531      32531    32581  6037125310  6059088602             1           505   
848008    848008   849150  6037125310  6059088701             1           505   
1665901  1665901  1668132  6059088701  6037125310             1            46   

         fips_2_users     ri  dir_pci                       o_d  
80829             505  4.385    1.980  6037125310.06059075303.0  
617762            103  4.385    9.709  6037125310.06059075303.0  
731480             65  5.519   15.385  6037125310.06059075401.0  
1597036           505  5.519    1.980  6037125310.06059075401.0  
350063            505  3.855    3.960  6037125310.06059075505.0  
...               ...    ...      ...                       ...  
1982543            79  5.007   12.658  6037125310.06059088601.0  
1910820           505  2.064    1.980  6037125310.06059088602.0  
32531             465  2.064    2.151  6037125310.06059088602.0  
848008             46  6.561   21.739  6037125310.06059088701.0  
1665901           505  6.561    1.980  6037125310.06059088701.0  

[100 rows x 10 columns]

In [21]:
odd = s[1::2]

In [22]:
gby = odd.groupby('o_d')['o_d'].count().to_frame()

In [23]:
gby['o_d'].max()

1

In [24]:
gby['o_d'].min()

1

In [25]:
odd

level_0    index      o_fips      d_fips  shared_users  fips_1_users  \
1021252  1021252  1022621  6037101210  6037101110             3           115   
240814    240814   241142  6037101110  6037101220             1            25   
410425    410425   410998  6037101400  6037101110             1            63   
1432444  1432444  1434352  6037101110  6037103102             2            25   
116060    116060   116228  6037101110  6037106407             1            25   
...          ...      ...         ...         ...           ...           ...   
1117938  1117938  1119439  6071002105  6071002017             2           148   
248239    248239   248579  6071002103  6071002101             2            20   
1814519  1814519  1816940  6071002101  6071002105             5            38   
172534    172534   172768  6071002105  6071002103             6           148   
596073    596073   596901  6071002105  6071012200             1           148   

         fips_2_users       ri  dir_pci                       o_d  
1021252            25   55.950  120.000  6037101110.06037101210.0  
240814             14   53.452   71.429  6037101110.06037101220.0  
410425             25   25.198   40.000  6037101110.06037101400.0  
1432444            82   44.173   24.390  6037101110.06037103102.0  
116060             14   53.452   71.429  6037101110.06037106407.0  
...               ...      ...      ...                       ...  
1117938            50   23.250   40.000  6071002017.06071002105.0  
248239             38   72.548   52.632  6071002101.06071002103.0  
1814519           148   66.673   33.784  6071002101.06071002105.0  
172534             20  110.282  300.000  6071002103.06071002105.0  
596073             79    9.248   12.658  6071002105.06071012200.0  

[1044541 rows x 10 columns]

In [28]:
odd.to_csv(r'K:\OneDrive_USC\OneDrive - University of South Carolina\Research\place_connectivity\LA_SCI_2019_directed.csv', index=False)

# AgglomerativeClustering

In [125]:
import pandas as pd
import sklearn
from sklearn.cluster import AgglomerativeClustering
import numpy as np
from natsort import natsorted
import os

import plotly.express as px
import json
from urllib.request import urlopen

with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)
    
def drawmap(df_re):
    fig = px.choropleth_mapbox(df_re, geojson=counties, locations='fips', color='class',
#                                color_discrete_map="Viridis",
#                                color = 'class'
                               range_color=(0, 50),
                               mapbox_style="carto-positron",
                               zoom=3, center = {"lat": 37.0902, "lon": -95.7129},
                               opacity=0.5,
                               labels={'unemp':'unemployment rate'}
                              )
    fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    fig.show()   

    
def list_to_file(a_list, file_name):
    with open(file_name, mode='w', encoding='utf-8') as myfile:
        a_list = [str(x) for x in a_list]
        myfile.write('\n'.join(a_list))
        myfile.write('\n')

## No need to create directed graph

In [299]:
data_path = r'K:\OneDrive_USC\OneDrive - University of South Carolina\Research\place_connectivity\0223\Place-Connectivity-Index'
file_name = r'US_CensusTract_NewYorkCity_PCI_2019.csv'
# file_name = r'US_CensusTract_LosAngeles_PCI_2019.csv'
csv_file = os.path.join(data_path, file_name)
df = pd.read_csv(csv_file, dtype={"place_i":str, "place_j":str})
df

place_i      place_j  shared_users  place_i_users  place_j_users  \
0        36005024900  36081039400             1            114             61   
1        36005012102  36081000100             1              7            995   
2        36047059300  36061008000             1             19           1327   
3        36005039500  36081044301             1             64             25   
4        36081062900  36061027100             2             89            221   
...              ...          ...           ...            ...            ...   
1053189  36061009600  36081049302             7           4647             39   
1053190  36061022500  36047021500             1            302             66   
1053191  36047051400  36005008700             2            516            153   
1053192  36047107000  36047015400             1            149             63   
1053193  36047114201  36047062000             1             59             80   

            pci  dir_pci  
0        11.992   16.393  
1        11.982    1.005  
2         6.298    0.754  
3        25.000   40.000  
4        14.261    9.050  
...         ...      ...  
1053189  16.443  179.487  
1053190   7.083   15.152  
1053191   7.118   13.072  
1053192  10.321   15.873  
1053193  14.556   12.500  

[1053194 rows x 7 columns]

## filter dataframe

In [288]:
tweet_user_min = 5

df = pd.read_csv(csv_file, dtype={"place_i":str, "place_j":str})
print("Rows count before filtering:", len(df))

gby_o = df.groupby('place_i')['place_i'].count().index.to_list()
gby_d = df.groupby('place_j')['place_j'].count().index.to_list()
gby = gby_o + gby_d
gby_list = gby_o + gby_d
gby_set = set(gby_list)
gby_list = list(gby_set)
place_list = natsorted(gby_list)
print("Place counts (before filtering): ", len(place_list))
print()


# fitler
print("tweet_user_min:", tweet_user_min)
df = pd.read_csv(csv_file, dtype={"place_i":str, "place_j":str})

df = df[df['place_i'] != df['place_j']]
df = df[df['place_i_users'] > tweet_user_min]
df = df[df['place_j_users'] > tweet_user_min]
print("Rows count after filtering:", len(df))

gby_o = df.groupby('place_i')['place_i'].count().index.to_list()
gby_d = df.groupby('place_j')['place_j'].count().index.to_list()
gby = gby_o + gby_d
gby_list = gby_o + gby_d
gby_set = set(gby_list)
gby_list = list(gby_set)
place_list = natsorted(gby_list)
print("Place counts (after filtering): ", len(place_list))


Rows count before filtering: 1053194
Place counts (before filtering):  2040

tweet_user_min: 5
Rows count after filtering: 1028318
Place counts (after filtering):  1863


In [289]:
new_name = csv_file.replace(".csv", "_placelist.csv")
list_to_file(place_list, new_name)

## build distance matrix

In [290]:
dis_mat = np.zeros((len(place_list[:]), len(place_list[:])))
print("dis_mat shape:", dis_mat.shape) 
print()

place_dic = {}                
for i in range(len(place_list[:])):
#     print(i, gby_list[i])
    place_dic[place_list[i]] = i
# print(fips_dic)

print("place dictionary: ")
print("idx, key, place_dic[key]")
for idx, key in enumerate(place_dic.keys()):
    print(idx, key, place_dic[key])

dis_mat shape: (1863, 1863)

place dictionary: 
idx, key, place_dic[key]
0 36005000100 0
1 36005000200 1
2 36005000400 2
3 36005001600 3
4 36005001900 4
5 36005002000 5
6 36005002300 6
7 36005002400 7
8 36005002500 8
9 36005002701 9
10 36005002702 10
11 36005002800 11
12 36005003100 12
13 36005003300 13
14 36005003500 14
15 36005003700 15
16 36005003900 16
17 36005004100 17
18 36005004200 18
19 36005004300 19
20 36005004400 20
21 36005004600 21
22 36005004800 22
23 36005005001 23
24 36005005002 24
25 36005005100 25
26 36005005200 26
27 36005005300 27
28 36005005400 28
29 36005005600 29
30 36005005902 30
31 36005006000 31
32 36005006100 32
33 36005006200 33
34 36005006300 34
35 36005006400 35
36 36005006500 36
37 36005006700 37
38 36005006800 38
39 36005006900 39
40 36005007000 40
41 36005007100 41
42 36005007200 42
43 36005007300 43
44 36005007400 44
45 36005007500 45
46 36005007600 46
47 36005007700 47
48 36005007800 48
49 36005007900 49
50 36005008300 50
51 36005008500 51
52 36005008

441 36047016100 441
442 36047016200 442
443 36047016300 443
444 36047016400 444
445 36047016500 445
446 36047016600 446
447 36047016700 447
448 36047016900 448
449 36047017000 449
450 36047017100 450
451 36047017200 451
452 36047017400 452
453 36047017500 453
454 36047017600 454
455 36047017700 455
456 36047017800 456
457 36047017900 457
458 36047018000 458
459 36047018100 459
460 36047018200 460
461 36047018300 461
462 36047018501 462
463 36047018600 463
464 36047018700 464
465 36047019000 465
466 36047019100 466
467 36047019200 467
468 36047019300 468
469 36047019400 469
470 36047019500 470
471 36047019600 471
472 36047019700 472
473 36047019800 473
474 36047019900 474
475 36047020000 475
476 36047020100 476
477 36047020300 477
478 36047020400 478
479 36047020500 479
480 36047020600 480
481 36047020700 481
482 36047021000 482
483 36047021100 483
484 36047021200 484
485 36047021300 485
486 36047021400 486
487 36047021500 487
488 36047021700 488
489 36047021800 489
490 36047021900 490


1031 36061003602 1031
1032 36061003700 1032
1033 36061003800 1033
1034 36061003900 1034
1035 36061004000 1035
1036 36061004100 1036
1037 36061004200 1037
1038 36061004300 1038
1039 36061004400 1039
1040 36061004500 1040
1041 36061004700 1041
1042 36061004800 1042
1043 36061004900 1043
1044 36061005000 1044
1045 36061005200 1045
1046 36061005400 1046
1047 36061005501 1047
1048 36061005502 1048
1049 36061005600 1049
1050 36061005700 1050
1051 36061005800 1051
1052 36061005900 1052
1053 36061006000 1053
1054 36061006100 1054
1055 36061006200 1055
1056 36061006300 1056
1057 36061006400 1057
1058 36061006500 1058
1059 36061006600 1059
1060 36061006700 1060
1061 36061006800 1061
1062 36061006900 1062
1063 36061007000 1063
1064 36061007100 1064
1065 36061007200 1065
1066 36061007300 1066
1067 36061007400 1067
1068 36061007500 1068
1069 36061007600 1069
1070 36061007700 1070
1071 36061007800 1071
1072 36061007900 1072
1073 36061008000 1073
1074 36061008100 1074
1075 36061008200 1075
1076 36061

1637 36081062100 1637
1638 36081062200 1638
1639 36081062500 1639
1640 36081062600 1640
1641 36081062700 1641
1642 36081062900 1642
1643 36081063000 1643
1644 36081063200 1644
1645 36081063302 1645
1646 36081063500 1646
1647 36081063700 1647
1648 36081063800 1648
1649 36081063900 1649
1650 36081064101 1650
1651 36081064102 1651
1652 36081064500 1652
1653 36081064600 1653
1654 36081065000 1654
1655 36081065400 1655
1656 36081065600 1656
1657 36081065702 1657
1658 36081065703 1658
1659 36081066000 1659
1660 36081066100 1660
1661 36081066300 1661
1662 36081066400 1662
1663 36081066501 1663
1664 36081067100 1664
1665 36081067900 1665
1666 36081068000 1666
1667 36081068200 1667
1668 36081068300 1668
1669 36081068700 1669
1670 36081069300 1670
1671 36081069400 1671
1672 36081069500 1672
1673 36081069701 1673
1674 36081069702 1674
1675 36081070300 1675
1676 36081070700 1676
1677 36081070900 1677
1678 36081071100 1678
1679 36081071303 1679
1680 36081071304 1680
1681 36081071305 1681
1682 36081

In [291]:
for idx, row in df.iterrows():
    interval = 100000
    i = place_dic[row['place_i']]
    j = place_dic[row['place_j']]
    i = int(i)
    j = int(j)
    dis_mat[i, j] = row['pci']
    dis_mat[j, i] = row['pci']
    if idx % interval == 0:
        print("idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']")
        print(idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j'])
    if i == j:
        dis_mat[j, i] = 0
        
print("done")

idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']
0 177 1520 11.992 11.992 36005024900 36081039400
idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']
100000 110 722 13.333 13.333 36005018302 36047050400
idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']
200000 1109 510 5.023 5.023 36061011401 36047024500
idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']
300000 1129 1030 23.779 23.779 36061013400 36061003601
idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']
400000 1028 1311 4.203 4.203 36061003300 36081004401
idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']
600000 341 1584 3.635 3.635 36047002100 36081051100
idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']
700000 500 1252 2.805 2.805 36047023300 36061025100
idx, i, j, dis_mat[i, j], dis_mat[j, i], row['place_i'], row['place_j']
800000 1787 435 9.252 9.252 36081107202 36047015300
idx, i

In [292]:
import scipy
matrix_file = csv_file.replace(".csv", "_matrix.npz")
s_dis_mat = scipy.sparse.coo_matrix(dis_mat)
scipy.sparse.save_npz(matrix_file, s_dis_mat, compressed=True)

In [293]:
print("dis_mat.sum(), df['pci'].sum():", dis_mat.sum(), df['pci'].sum())

dis_mat.sum(), df['pci'].sum(): 19677577.45400001 19677577.454000004


## AgglomerativeClustering

In [294]:
print("dis_mat.max(), dis_mat.min():", (dis_mat.max(), dis_mat.min()))

dis_mat.max(), dis_mat.min(): (377.964, 0.0)


In [295]:
dis_mat_inv = 1 / (dis_mat/1000 + 0.0000001)
# dis_mat_inv = 1 / (dis_mat + 0.0000001)

print("dis_mat_inv:\n", dis_mat_inv)


dis_mat_inv:
 [[1.00000000e+07 5.74280283e+01 6.67998210e+01 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 [5.74280283e+01 1.00000000e+07 5.64961857e+00 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 [6.67998210e+01 5.64961857e+00 1.00000000e+07 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 ...
 [1.00000000e+07 1.00000000e+07 1.00000000e+07 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 [1.00000000e+07 1.00000000e+07 1.00000000e+07 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 [1.00000000e+07 1.00000000e+07 1.00000000e+07 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]]


In [296]:
conn_mat = np.where(dis_mat > 0, 1, 0)
print("conn_mat:\n", conn_mat)
print("conn_mat.sum():", conn_mat.sum())

conn_mat:
 [[0 1 1 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
conn_mat.sum(): 1028318


## with connectivity, linkage = 'average'

In [300]:
import scipy
data_path = r'K:\OneDrive_USC\OneDrive - University of South Carolina\Research\place_connectivity\0223\Place-Connectivity-Index'
maxtrix_file = os.path.join(data_path, r'US_CensusTract_NewYorkCity_PCI_2019_matrix.npz')
# maxtrix_file = os.path.join(data_path, r'US_CensusTract_LosAngeles_PCI_2019_matrix.npz')


s_dis_mat = scipy.sparse.load_npz(maxtrix_file)

place_file = maxtrix_file.replace("_matrix.npz", "_placelist.csv")
place_list = pd.read_csv(place_file, header=None, names=['place'])['place'].to_list()
dis_mat = s_dis_mat.todense()
np.fill_diagonal(dis_mat, 0)

print("dis_mat.shape:", dis_mat.shape)

print("dis_mat:\n", dis_mat)
print()
print("len(place_list), place_list:\n", len(place_list), "\n", place_list)

dis_mat.shape: (1863, 1863)
dis_mat:
 [[  0.     17.413  14.97  ...   0.      0.      0.   ]
 [ 17.413   0.    177.003 ...   0.      0.      0.   ]
 [ 14.97  177.003   0.    ...   0.      0.      0.   ]
 ...
 [  0.      0.      0.    ...   0.      0.      0.   ]
 [  0.      0.      0.    ...   0.      0.      0.   ]
 [  0.      0.      0.    ...   0.      0.      0.   ]]

len(place_list), place_list:
 1863 
 [36005000100, 36005000200, 36005000400, 36005001600, 36005001900, 36005002000, 36005002300, 36005002400, 36005002500, 36005002701, 36005002702, 36005002800, 36005003100, 36005003300, 36005003500, 36005003700, 36005003900, 36005004100, 36005004200, 36005004300, 36005004400, 36005004600, 36005004800, 36005005001, 36005005002, 36005005100, 36005005200, 36005005300, 36005005400, 36005005600, 36005005902, 36005006000, 36005006100, 36005006200, 36005006300, 36005006400, 36005006500, 36005006700, 36005006800, 36005006900, 36005007000, 36005007100, 36005007200, 36005007300, 36005007400, 36

In [301]:
dis_mat_inv = 1 / (dis_mat/1000 + 0.0000001)
 
print("dis_mat_inv:\n", dis_mat_inv) 

conn_mat = np.where(dis_mat > 0, 1, 0)


dis_mat_inv:
 [[1.00000000e+07 5.74280283e+01 6.67998210e+01 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 [5.74280283e+01 1.00000000e+07 5.64961857e+00 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 [6.67998210e+01 5.64961857e+00 1.00000000e+07 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 ...
 [1.00000000e+07 1.00000000e+07 1.00000000e+07 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 [1.00000000e+07 1.00000000e+07 1.00000000e+07 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]
 [1.00000000e+07 1.00000000e+07 1.00000000e+07 ... 1.00000000e+07
  1.00000000e+07 1.00000000e+07]]


In [302]:

df_re_list = []

n_cluster_cnts = [5, 10, 20, 30, 40, 50, 60, 80, 100]
results_df = pd.DataFrame(list(zip(place_list)), columns =['place'])
for n in n_cluster_cnts:
    name = "n_" + str(n)
    results_df[name] = -1

for n_clusters in n_cluster_cnts:
# for n_clusters in (5, ):
    clustering = AgglomerativeClustering(n_clusters=n_clusters,  affinity="precomputed", linkage='average', \

                                       connectivity=conn_mat).fit(dis_mat_inv)


    fips_col = []
    for idx, label in enumerate(clustering.labels_[:]):
    #     print(gby_list[idx], label)
        
        fips_col.append(gby_list[idx])

#     df_re = pd.DataFrame(list(zip(fips_col, clustering.labels_[:])), columns=['fips', 'class'])
    name = "n_" + str(n_clusters)
    results_df[name] = clustering.labels_


    print("finished ", n_clusters)

    
new_file = matrix_file.replace("_matrix.npz", "_agglomerative.csv")
    
results_df.to_csv(new_file, index=False)

finished  5
finished  10
finished  20
finished  30
finished  40
finished  50
finished  60
finished  80
finished  100
